General:
    MODEL_NAME: AB_MIL_MIXUP
    seed: 2024
    num_classes: 2
    num_epochs: 50
    device: 0
    num_workers: 4
    best_model_metric: macro_auc
    earlystop: 
        use: True
        patience: 10
        metric: macro_auc

Dataset:
    DATASET_NAME: your_dataset_name
    dataset_csv_path: /path/to/your/dataset.csv
    balanced_sampler:
        use: False
        replacement: True

Logs:
    log_root_dir: /path/to/your/log_dir/mixup_results

Model:
    in_dim: 1024
    L: 512
    D: 128
    dropout: 0.25
    act: relu
    optimizer:
        which: adam
        adam_config:
            lr: 0.0002
            weight_decay: 0.00001
    criterion: bce  # Use BCE for soft labels
    scheduler:
        warmup: 2
        which: cosine
        cosine_config:
            T_max: 20
            eta_min: 0.00001

Mixup:
    method: mixup  # Standard Mixup
    alpha: 1.0
    prob: 0.5

