General:
    MODEL_NAME: RET_MIL
    seed: 42
    num_classes: 2
    num_epochs: 5
    device: 0
    num_workers: 4
    best_model_metric: macro_auc
    earlystop:
        use: False
        patience: 5
        metric: macro_auc

Dataset:
    DATASET_NAME: CAMELYON
    dataset_csv_path: /mnt/net_sda/Public_Dataset/CAMELYON+/splits/CAMELYON/Total_5-fold_CAMELYON_1fold.csv
    balanced_sampler:
        use: False
        replacement: True

Logs:
    log_root_dir: /data_sde/zbr/MIL_BASELINE/test_results_ret_mil_20260118_062305

Model:
    in_dim: 512  # CONCH features
    embed_dim: null  # 如果为 null，则等于 in_dim
    chunk_len: 512  # local subsequence 长度
    num_heads: 8  # retention heads 数量
    dropout: 0.25
    optimizer:
        which: adam
        adam_config:
            lr: 0.0002
            weight_decay: 0.00001
    criterion: ce
    scheduler:
        warmup: 2
        which: step
        step_config:
            step_size: 3
            gamma: 0.9
